/**
 * Ledger event types.
 *
 * Names deliberately mirror the City::Sync contract suite so the app's
 * history can later be replayed onto chain modules:
 *
 *   IssuerRegistry / RedeemerRegistry  -> ORG_*
 *   IssuerWaiverRegistry               -> WAIVER_*
 *   OpportunityManager                 -> TASK_* / CLAIM_* / COMPLETION_*
 *   CityToken (soul-bound mint/burn)   -> CREDITS_MINTED / CREDITS_BURNED
 *   Redemption                         -> REDEMPTION_*
 */
export const EventTypes = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_PROFILE_UPDATED: 'USER_PROFILE_UPDATED',
  IDENTITY_CREATED: 'IDENTITY_CREATED',
  ORG_AUTHORITY_GRANTED: 'ORG_AUTHORITY_GRANTED',
  ORG_AUTHORITY_REVOKED: 'ORG_AUTHORITY_REVOKED',
  ORG_INVITE_CREATED: 'ORG_INVITE_CREATED',
  ORG_INVITE_ACCEPTED: 'ORG_INVITE_ACCEPTED',
  ORG_ROLE_CREATED: 'ORG_ROLE_CREATED',
  ORG_ROLE_UPDATED: 'ORG_ROLE_UPDATED',
  ORG_REGISTERED: 'ORG_REGISTERED',
  ORG_APPROVED: 'ORG_APPROVED',
  ORG_SUSPENDED: 'ORG_SUSPENDED',
  ORG_PROFILE_UPDATED: 'ORG_PROFILE_UPDATED', // editorial audit only — carries no financial meaning
  CITY_LAUNCH_REQUESTED: 'CITY_LAUNCH_REQUESTED',
  CITY_LAUNCH_APPROVED: 'CITY_LAUNCH_APPROVED',
  CITY_LAUNCH_REJECTED: 'CITY_LAUNCH_REJECTED',
  CITY_LAUNCH_OWNER_ASSIGNED: 'CITY_LAUNCH_OWNER_ASSIGNED',
  CREDENTIAL_GRANTED: 'CREDENTIAL_GRANTED',
  CREDENTIAL_REVOKED: 'CREDENTIAL_REVOKED',
  CATALOG_ENTRY_SUBMITTED: 'CATALOG_ENTRY_SUBMITTED',
  CATALOG_ENTRY_APPROVED: 'CATALOG_ENTRY_APPROVED',
  CATALOG_ENTRY_REJECTED: 'CATALOG_ENTRY_REJECTED',
  CATALOG_ENTRY_CHANGES_REQUESTED: 'CATALOG_ENTRY_CHANGES_REQUESTED',
  WAIVER_VERSION_CREATED: 'WAIVER_VERSION_CREATED',
  WAIVER_ACCEPTED: 'WAIVER_ACCEPTED',
  TASK_CREATED: 'TASK_CREATED',
  ONBOARDING_SESSION_CREATED: 'ONBOARDING_SESSION_CREATED',
  TASK_CLOSED: 'TASK_CLOSED',
  TASK_REOPENED: 'TASK_REOPENED',
  SHIFT_CREATED: 'SHIFT_CREATED',
  SHIFT_CLOSED: 'SHIFT_CLOSED',
  TASK_CLAIMED: 'TASK_CLAIMED',
  CLAIM_UNCLAIMED: 'CLAIM_UNCLAIMED',
  CLAIM_CHECKED_IN: 'CLAIM_CHECKED_IN',
  CLAIM_NO_SHOW: 'CLAIM_NO_SHOW',
  COMPLETION_SUBMITTED: 'COMPLETION_SUBMITTED',
  COMPLETION_VERIFIED: 'COMPLETION_VERIFIED',
  COMPLETION_REJECTED: 'COMPLETION_REJECTED',
  CREDITS_MINTED: 'CREDITS_MINTED',
  CREDITS_BURNED: 'CREDITS_BURNED',
  OFFERING_CREATED: 'OFFERING_CREATED',
  OFFERING_UPDATED: 'OFFERING_UPDATED',
  REDEMPTION_REQUESTED: 'REDEMPTION_REQUESTED',
  REDEMPTION_FINALIZED: 'REDEMPTION_FINALIZED',
  REDEMPTION_CANCELLED: 'REDEMPTION_CANCELLED',
  ANCHOR_CREATED: 'ANCHOR_CREATED',
  POST_CREATED: 'POST_CREATED',
  POST_HEARTED: 'POST_HEARTED',
  POST_UNHEARTED: 'POST_UNHEARTED',
  VOLUNTEER_GROUP_CREATED: 'VOLUNTEER_GROUP_CREATED',
  VOLUNTEER_GROUP_MEMBERS_UPDATED: 'VOLUNTEER_GROUP_MEMBERS_UPDATED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  POST_REMOVED: 'POST_REMOVED',
  USER_DISABLED: 'USER_DISABLED',
  USER_ENABLED: 'USER_ENABLED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  CREDITS_ADJUSTED: 'CREDITS_ADJUSTED',
} as const

export type EventType = (typeof EventTypes)[keyof typeof EventTypes]
